server {
    host 127.0.0.1
    listen 8090
    server_name example.com

    root ./WWW
    index index.html
    error_page 400 ./WWW/err/400.html
    error_page 403 ./WWW/err/403.html
    error_page 404 ./WWW/err/404.html
    error_page 405 ./WWW/err/405.html
    error_page 500 ./WWW/err/500.html
    error_page 501 ./WWW/err/501.html
    client_max_body_size 10000000
    autoindex off

    location /uploads {
        root ./WWW/uploads
        allow GET POST DELETE
        upload on
        upload_path ./WWW/uploads
        autoindex on
    }

    location /cgi-bin {
        root ./WWW/cgi-bin
        allow GET POST
        cgi on
        cgi_upload_path ./WWW/uploads/cgi
    }

    location / {
        root ./WWW
        index index.html
        allow GET POST DELETE
    }
}
