#!/usr/bin/env python3
import os

cgi_vars = [
    "REQUEST_METHOD", "SCRIPT_NAME", "QUERY_STRING", "SERVER_PROTOCOL",
    "SERVER_SOFTWARE", "SERVER_NAME", "SERVER_PORT", "REMOTE_ADDR",
    "CONTENT_TYPE", "CONTENT_LENGTH", "GATEWAY_INTERFACE",
]
http_headers = sorted(k for k in os.environ if k.startswith("HTTP_"))

rows = ""
for name in cgi_vars:
    rows += "<tr><td>%s</td><td>%s</td></tr>\n" % (name, os.environ.get(name, ""))
for name in http_headers:
    rows += "<tr><td>%s</td><td>%s</td></tr>\n" % (name, os.environ.get(name, ""))

body = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>CGI info</title>
<style>
body {{ font-family: ui-monospace, monospace; max-width: 42rem; margin: 3rem auto; padding: 0 1.5rem; }}
table {{ border-collapse: collapse; width: 100%; }}
td {{ border-bottom: 1px solid rgba(127,127,127,0.3); padding: 0.3rem 0.6rem; word-break: break-all; }}
td:first-child {{ color: #2b7de9; white-space: nowrap; }}
</style></head>
<body>
<p>This page was generated by <code>/cgi-bin/info.py</code>, executed by <code>fork()</code>+<code>execve()</code> and
streamed back over a real non-blocking pipe registered on the server's own epoll instance - not read from a temp file.</p>
<table>
{rows}
</table>
<p><a href="/">back</a></p>
</body></html>
""".format(rows=rows)

import sys
sys.stdout.write("Content-Type: text/html\r\n")
sys.stdout.write("Content-Length: %d\r\n" % len(body))
sys.stdout.write("\r\n")
sys.stdout.write(body)
